config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root to: 'pages#home'

  devise_for :users


  resources :events, except: [:destroy]

  resources :profiles, only: [:new, :edit, :create, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
has_and_belongs_to_many :categories
belongs_to :user


validates :name, presence: true, length: { maximum: 50 }
validates :description, presence: true, length: { maximum: 500 }
#validates :location, presence: true
#validates :price, presence: true
#validates :capacity, presence: true
#validates :includes_food, presence: true
#validates :includes_drinks, presence: true
#validates :starts_at, presence: true, datetime:
#validates :ends_at, presence: true, datetime:
#validates :active,

  def bargain?
    price < 30
  end

  def self.order_by_price
    order :price
  end


has_many :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :events, dependent: :destroy

    has_one :profile

    def full_name
      return profile.full_name if profile?

        email
      end

    def profile?
        profile.present? && profile.persisted?
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # The before_action :authenticate_user!, except: [:show] makes sure that the
  # user is authenticated before calling any of the actions in the controller,
  # except the show method. In other words: If you're not logged in, you can only
  # use the show method of the eventsController, but not use any of its other
  # methods. :)

  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

# Normally the index action will return all events. In this case, we only want to
# show the events that belong to the current user. Or, as programmers tend to
# say, we use the events that are scoped on the current user. The current_user
# is set by the previous mentioned method.

# The method definition for show and edit look a bit silly.
# They only need to run the code from the before_action, nothing else.
# The one-line form def show; end is just a way of over-communicating to
# your colleagues that the method is needed, but empty.

# Read
  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
    @photos = @event.photos
  end

# Work your way down the according to CRUD
# Create

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "Event created!"
    else
      render :new
    end
  end

# Update edit -> :form // update -> :change state

  def edit
      if current_user.id == @event.user.id
        @photos = @event.photos
      else
        redirect_to root_path, notice: "You don't have permission."
      end
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "event successfully updated"
    else
      render :edit
    end
  end

# Destroy( not in this case)

  private

  def image_params
    params[:images].present? ? params.require(:images) : []
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params
      .require(:event)
      .permit( :name, :description, :location, :price, :capacity, :includes_food,
      :includes_drinks, :starts_at, :ends_at, :active, category_ids: []
    )
  end
end


# Using the event_params method, only the attributes that are permit-ed for a
# resource that is require-d, we can assign these attributes. This is also
# known as whitelisting. The event_params method is like a bouncer: if your
# trying to sneak in while you're not permitted, you won't be let in!

# This means that you'll have a single place where you're making conscious
# decision about which attributes to allow from your users. This is a security
# practice to help prevent accidentally allowing users to update sensitive
# model attributes.

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/helpers/categories_helper.rb
module CategoriesHelper
end

app/controllers/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!

  end
end

app/controllers/helpers/events_helper.rb
module EventsHelper
end

app/controllers/helpers/pages_helper.rb
module PagesHelper
end

app/controllers/helpers/profiles_helper.rb
module ProfilesHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

    private

    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/events/_form.html.erb
<%#= form_for @event do |f| %>
<%= form_for @event, html: { multipart: true } do |f| %>

    <div class="form-group">
      <label>Event name</label>
      <%= f.text_field :name, placeholder: "Event name", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Description</label>
      <%= f.text_area :description, rows: 5, placeholder: "Say something about your event", class: "form-control" %>
    </div>

      <label>Publish this place?</label>

      <div class="form-group">
        <%= f.check_box :active %> Active
      </div>

    <label>Photos</label>

      <div class="form-group">
        <span class="btn btn-default">
          Upload Photos
          <%= file_field_tag "images[]", type: :file, multiple: true %>
        </span>
      </div>

      <div id="photos">
        <%= render 'photos/list' %>
      </div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>

<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Events", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 eveight">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
      </div>
      <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <!-- Categories -->
    <h4>Category</h4>
      <% @categories.each do |category| %>
        <span class="label label-success"><%= category.name %></span>
      <% end %>

    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>

    <h4>Photos</h4>
    <% @event.photos.each do |photo| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= image_tag photo.image.thumbnail %>
        </div>
      </div>
    <% end %>

  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">

      <h2>About</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper.
         Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>



  </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">

    <h2>Contact</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper.
      Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>


  </div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>


    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
<h1>Welcome</h1>
<br>
<br>
<br>
<br>
<h3>...where memories are created</h3>
  </body>
  <footer class="block">
      <p>Made by: Caspar Boetes</p>
      <p>Contact information: casparboetes@gmail.com</p>
  </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>


</html>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <span class="btn btn-default">Delete</span>
        <%= link_to "Delete", photo_path( photo.id ), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.full_name %> <span class="caret"></span></a>

              <ul class="dropdown-menu">
                <li><%= link_to "Your Events", events_path %></li>
                <li role="separator" class="divider"></li>

                  <% if current_user.profile? %>
                    <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
                  <% else %>
                    <li><%= link_to "Create Profile", new_profile_path %></li>
                  <% end %>
                <li><%= link_to "Edit Password", edit_user_registration_path %></li>

                <li role="separator" class="divider"></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>

          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>